### ISSUE TITLE
Links in Documentation not Working

### ISSUE THREAD

**Issue by herostrat** [okkur/website#7]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug 

**What happened**:
Example: Go to https://about.okkur.org/syna/docs/fragments/#built-in-fragments and click on the fragments link, which points to https://about.okkur.org/fragments and is a 404

Many other links are affected, too.

**Environment**:
- Okkur Labs Website version:  Currently served version
- Others:

**Comment by stp-ip** [comment]
Thanks for reporting. That's due to merging the exampleSite from okkur/syna, which we use as demo and docs site at the same time into the okkur page. This leads to a subdirectory, which the links don't reflect as they are more hardcoded than they should be.

They are currently using Markdown links, but should be using the `ref` from Hugo within markdown. Haven't checked it out, if it works perfectly with our fragments, but it should be something along the lines of: `{{< ref "fragments" >}}`.

Will check it out myself, but happy to review a PR on github.com/okkur/syna, if you would love helping out.

@mpourismaiel might be able to help with a suggestion as well.

**Comment by stp-ip** [comment]
Already temporarily fixed within site. Underlying issue created as well. Closing this.
